<?php
namespace coldfox\dropzone;


class DropZoneUploadAction extends UploadAction {

    public function run() {
        set_time_limit(1800);
        return parent::run(); // TODO: Change the autogenerated stub
    }
}